export const FETCH_STATISTIC_DATA_START = 'FETCH_STATISTIC_DATA_START'
export const FETCH_STATISTIC_DATA_SUCCESS = 'FETCH_STATISTIC_DATA_SUCCESS'
export const FETCH_STATISTIC_DATA_ERROR = 'FETCH_STATISTIC_DATA_ERROR'
